export const errorMessages = {
  emailValid: "The input is not valid e-mail!",
  emailRequired: "Please input your e-mail!",
  passwordRequired: "Please input your password!",
  passwordMinLength: "Password must be at least 8 characters",
  passwordMaxLength: "Password length must not exceed 16 characters",
  fullNameRequired: "Please input your full name!",
  descRequired: "Please input description!",
  statusRequired: "Please choose one!",
  titleRequired: "Please input title!",
  urlImgValid: "The input is not valid url!",
  urlImgRequired: "Please input url image",
  confirmPasswordRequired: "Please retype your password",
  confirmPasswordValid: "Your passwords do not match",
};
